'use client';
import { useEffect, useState } from 'react';
import { createOrder } from '@/lib/store';
import { OrderItem, Order } from '@/lib/types';
const CART_KEY='printing_cart_v1'; const waStore=process.env.NEXT_PUBLIC_WHATSAPP||'6281240322071';
export default function Checkout(){const [items,setItems]=useState<OrderItem[]>([]);const [done,setDone]=useState<Order|null>(null);const [form,setForm]=useState({name:'',wa:'',fulfillment:'pickup',address:'',notes:''});useEffect(()=>setItems(JSON.parse(localStorage.getItem(CART_KEY)||'[]')),[]);const total=items.reduce((s,i)=>s+i.price*i.qty,0);
 async function submit(e:React.FormEvent){e.preventDefault();if(!items.length)return;const now=new Date();const code=`PRT-${String(now.getFullYear()).slice(-2)}${String(now.getMonth()+1).padStart(2,'0')}${String(now.getDate()).padStart(2,'0')}-${Math.floor(100+Math.random()*900)}`;const order:Order={id:crypto.randomUUID(),code,customerName:form.name,whatsapp:form.wa,fulfillment:form.fulfillment as 'pickup'|'delivery',address:form.address,notes:form.notes,total,status:'Pesanan diterima',createdAt:now.toISOString(),items};await createOrder(order);localStorage.removeItem(CART_KEY);setDone(order)}
 if(done){const msg=`Halo, saya sudah membuat pesanan ${done.code} dengan total Rp${done.total.toLocaleString('id-ID')}. Mohon konfirmasi.`;return <main className="section"><div className="container" style={{maxWidth:650}}><div className="panel"><div className="status">PESANAN BERHASIL</div><h1>Kode pesanan: {done.code}</h1><p className="muted">Simpan kode ini untuk mengecek status pesanan.</p><div className="summary"><b>Total Rp{done.total.toLocaleString('id-ID')}</b></div><a className="btn accent" style={{marginTop:16}} href={`https://wa.me/${waStore}?text=${encodeURIComponent(msg)}`}>Konfirmasi via WhatsApp</a></div></div></main>}
 return <main className="section"><div className="container two"><div><div className="tag">CHECKOUT</div><h1>Selesaikan pesanan</h1><form className="form" onSubmit={submit}><div className="field"><label>Nama</label><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="field"><label>Nomor WhatsApp</label><input required placeholder="08xxxxxxxxxx" value={form.wa} onChange={e=>setForm({...form,wa:e.target.value})}/></div><div className="field"><label>Pengambilan</label><select value={form.fulfillment} onChange={e=>setForm({...form,fulfillment:e.target.value})}><option value="pickup">Ambil di toko</option><option value="delivery">Dikirim</option></select></div>{form.fulfillment==='delivery'&&<div className="field"><label>Alamat</label><textarea required rows={3} value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div>}<div className="field"><label>Catatan tambahan</label><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></div><button className="btn accent" disabled={!items.length}>Buat Pesanan</button></form></div><div className="summary"><h2>Ringkasan</h2>{items.length?items.map((i,idx)=><div key={idx} style={{padding:'12px 0',borderBottom:'1px solid var(--line)'}}><b>{i.productName}</b><div className="muted">{i.qty} × Rp{i.price.toLocaleString('id-ID')}</div>{i.notes&&<small>{i.notes}</small>}</div>):<p className="muted">Keranjang masih kosong.</p>}<h2>Total Rp{total.toLocaleString('id-ID')}</h2></div></div></main>}
